### PR TITLE
fix(core): Install vim-mode-plus-ex-mode when vim-mode-plus is enabled

### PR DESCRIPTION
**Pull request by xtian**

### CODE REVIEW

**Comment by dvcrn** [comment]
oh I didn't know there was a vim-mode-plus-ex-mode

**Comment by dvcrn** [comment]
Merged in https://github.com/dvcrn/proton/commit/df6a0601170833d3cbd9b875e470f3e7ef1ef6b3

**Comment by quarterto** [comment]
My 2¢: `vim-mode-plus-ex-mode` doesn't work well. It's lacking a lot of commands, and the UI isn't great. I have an open pull request with `ex-mode` (lloeki/ex-mode#137) to add `vim-mode-plus` compatibility (if it's not merged I might be persuaded to maintain a fork, depending on the demand).

**Comment by xtian** [comment]
@quarterto `ex-mode` does seem way better and seems to work fine. I assumed there was some major incompatibility between it and `vim-mode-plus` since `vim-mode-plus-ex-mode` is the one referenced in the `vim-mode-plus` README.

**Comment by quarterto** [comment]
I've been using my fork for a couple of weeks now and never noticed any problems.

**Comment by dvcrn** [comment]
If this is the case, I'm all in for a custom fork until the changes are merged in upstream. @quarterto can you publish your fork to apm and submit a PR? Would really love to get ex-mode into tomorrows release!

**Comment by quarterto** [comment]
I've just tried running the tests against vim-mode-plus and it is more incompatible than I hoped 😞  I might have time this weekend to properly fork and make it compatible.

**Pull request closed without merging**
