### PR TITLE
Port to shadow build

### PR DESCRIPTION
**Pull request by dvcrn**
Not sure if we'll go through with this. Treat it as an experiment.

### CODE REVIEW

**Comment by dvcrn** [comment]
@spencerlyon2  @geksilla since you both are contributors, now this is merged `cljsbuild` will get replaced by `shadow-build`. 

The only thing that changes is a faster build times and live-reload. Building changes to this command:
```
lein run -m build/dev # re-compiles with every change
lein run -m build/dev-once # one time build
lein run -m build/dev-repl # re-compiles code and reloads
lein run -m build/release # one time build + optimizations
```

Plus stuff is inside `src/cljs` now instead of `src/`

**Comment by spencerlyon2** [comment]
Awesome, trying it out now. 

So if I run `lein run -m build/dev-repl` I can just keep my atom running and it will load changes like magic?

**Comment by dvcrn** [comment]
Exactly! 🎩

**Comment by spencerlyon2** [comment]
```
[:client-connect "acf0a5a4-1b7a-44a1-a5c0-9cbad12fe7ad" :browser]
BROWSER: enabling package tabs
BROWSER: enabling package relative-numbers
BROWSER: init git
BROWSER: init clojure
BROWSER: init python
BROWSER: init julia
```

:mind-blown:

This is a game changer

**Comment by geksilla** [comment]
Awesome! Thanks @dvcrn and @thheller!

**Pull request merged**
