### PR TITLE
Python lang layer improvements.

### PR DESCRIPTION
**Pull request by geksilla**
- Added packages python-isort, python-tools
- Added new mode key bindings.

### CODE REVIEW

**Comment by spencerlyon2** [comment]
Should we include django in the default list here?

Spacemacs has a `frameworks` layer group with things like django, rails, and react.

**Comment by geksilla** [comment]
@spencerlyon2, agree. We need to check how better to implement frameworks section. I think for now it's ok if some frameworks specific packages will be included in language layer. @dvcrn what do you think about it?

**Comment by spencerlyon2** [comment]
Given that we don't add any keybindings or preferences for the django package, I'd probably vote to leave it off and suggest that users who want to have it to put it in their `~/.proton`

(I don't use django often and it seems like we are adding bloat for users in my boat)

**Comment by geksilla** [comment]
Created separate layer `:frameworks/django`.

**Pull request merged**
