### PR TITLE
Contribution guidelines

### PR DESCRIPTION
**Pull request by dvcrn**
Please add your ideas here

/cc @geksilla @Lknechtli

### CODE REVIEW

**Comment by geksilla** [comment]
What about to add some guidelines regarding commit message to generate beautiful and useful changelog, like [atom do](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#git-commit-messages). Here is a [tool](http://blog.thoughtram.io/announcements/tools/2014/09/18/announcing-clog-a-conventional-changelog-generator-for-the-rest-of-us.html) that we can use.

**Comment by dvcrn** [comment]
I am against emojis in commit messages. They obscure the actual task and add another layer of things possible contributors need to decipher.

The other parts I think are good. That convention you linked makes sense as well. Let's try to adopt some of it :)

**Comment by Lknechtli** [comment]
I like the look of clog. Thoughts re: git-flow?

**Comment by Lknechtli** [comment]
Once we get tests working, we may want to use something like travis-ci

**Comment by dvcrn** [comment]
Stole some stuff from the other documents. Anything else missing or stuff you guys want to add? 
 
We can't put unittests in there yet because we don't currently have anything contributors could integrate with. 

Git-flow, yes at some point but step by step. I first want to see how clog and unit tests affect the repository. I still don't see a reason why we should jump on git-flow right now. What benefits could it give us?

**Comment by Lknechtli** [comment]
The benefits to this don't really become apparent until you have a decent number of contributors, because it allows you to do things like accept pull requests to a development branch where it can be tested more thoroughly at the same time that you put a feature freeze on the release.

This can obviously be done without git-flow, but it's a sane default with tooling (wrapper around normal git commands) that is also easy to use without said tooling.  For basic contributions, the only change would be the commit naming strategy.

No particular reason to rush into it, but it's really easy to use and set up.

**Comment by Lknechtli** [comment]
at the same time, this post is a pretty good look at why we might not want to use it.
http://endoflineblog.com/gitflow-considered-harmful

**Comment by Lknechtli** [comment]
After further thought, I think that I agree with you that there isn't a compelling reason to switch to git-flow.

**Pull request merged**
