### PR TITLE
Added minimap toggle

### PR DESCRIPTION
**Pull request by spencerlyon2**

### CODE REVIEW

**Comment by dvcrn** [comment]
Minimap is currently only inside `~/.proton` (and the default template). I think we should either:
- add minimap to the core layer
- implement support for keybindings inside `~/.proton` and add it there

**Comment by spencerlyon2** [comment]
Another alternative would be to add a minimap layer that can activate other minimap related packages, perhaps based on minimap-layer specific config values

**Comment by dvcrn** [comment]
Sure, go for it! 

Maybe add a `proton.layers.tools` namespace or something like that to separate things from language layers

**Comment by dvcrn** [comment]
Did the namespacing part here https://github.com/dvcrn/proton/pull/24

**Comment by dvcrn** [comment]
I think this PR is no longer needed, right? We have a minimap layer now

**Pull request closed without merging**
