### PR TITLE
terminal layer

### PR DESCRIPTION
**Pull request by ericfode**
a layer for terminal
regarding #49

### CODE REVIEW

**Comment by dvcrn** [comment]
Cool! Do you want this merged directly or do you want to put commits on top?

**Comment by geksilla** [comment]
What about to change key binding to `SPC '`?

**Comment by ericfode** [comment]
@dvcrn what do you think about the key binding?

I'll rebase it tomorrow morning.
Thanks for reviewing!

**Comment by dvcrn** [comment]
Hmm. I think SPC \` feels more 'console like'. I'm not sure if fits into `t` for toggles since it is technically not a toggle but rather another UI on top. 

I'm gonna give SPC \` a try later and see how it feels

**Comment by richarddewit** [comment]
<kbd>SPC '</kbd> is the default keybinding for Spacemacs though

**Comment by ericfode** [comment]
Ohh I am going for the default spacemacs binding! Thank you Richard :+1:

**Comment by dvcrn** [comment]
@ericfode can you rebase master please?

**Comment by ericfode** [comment]
Done!

**Comment by dvcrn** [comment]
Cherry-picked in https://github.com/dvcrn/proton/commit/4f0f97b1f794d3cd142cd05ba5f24c8d779b1c8d

**Pull request closed without merging**
