### PR TITLE
feat(bufferNativateion): added buffer navigation

### LINKED ISSUE #279: Buffer navigation
I think there should be a buffer navigation for switching between tabs. Spacemacs has this functionality.

`SPACE + b + h` - Previous buffer (tab)
`SPACE + b + l` - Next buffer (tab)

Currently, Atom moves to the next buffer (tab) on `CTL + Page Up`.
Currently, Atom previous to the next buffer (tab) on `CTL + Page Down`.

### PR DESCRIPTION
**Pull request by jamrizzi**
This will fix #279

### CODE REVIEW

**Comment by jamrizzi** [comment]
This will fix #279

**Comment by dvcrn** [comment]
Thanks a lot for the PR! Could you squash your changes and format the message like [this](https://github.com/dvcrn/proton/blob/master/.github/CONTRIBUTING.md#commit-format)? Then I'll merge it right away

**Comment by jamrizzi** [comment]
I renamed the pull request, but can't figure out how to squash it.

**Comment by jamrizzi** [comment]
I renamed the pull request, but can't figure out how to squash it.

**Pull request merged**
