### PR TITLE
Display executed keystrokes and selected category.

### PR DESCRIPTION
**Pull request by geksilla**
output

### CODE REVIEW

**Comment by spencerlyon2** [comment]
LGTM -- nice work

**Comment by geksilla** [comment]
@spencerlyon2 thanks!

**Comment by dvcrn** [comment]
Looks like the other merged commits conflict with this one. Can you rebase?

**Comment by geksilla** [comment]
@dvcrn rebased.

**Comment by dvcrn** [comment]
:+1:

**Pull request merged**
