### PR TITLE
Allow <space> in non-editor windows. Fix #40

### LINKED ISSUE #40: Allow <space> in non-editor windows
Definitely a must. 

https://github.com/dvcrn/proton/issues/23

### PR DESCRIPTION
**Pull request by geksilla**

### CODE REVIEW

**Comment by spencerlyon2** [comment]
This gets close.  I can now use `spc` in the tree view, but not in an empty pane. 

I know that people don't have empty panes very often, but it would be nice if this would work anywhere we are not in insert mode

**Comment by geksilla** [comment]
Updated commit. Fixed issue with empty pane, also added `proton:toggleMode` command mapped to <kbd>,</kbd>.

**Comment by spencerlyon2** [comment]
What does `proton:toggleMode` do?

**Comment by geksilla** [comment]
Activates proton mode keymaps. Alias for 'SPC m'

**Comment by spencerlyon2** [comment]
ahh sorry, I forgot that was the name of the command.

Looks good ! :+1:

**Comment by spencerlyon2** [comment]
Actually, this is a bit too aggressive.

The Julia layer includes packages that provide a REPL inside atom and now I can't use `spc` in the REPL... Let me know how I can help you debug this

**Comment by geksilla** [comment]
Reproduced issue with julia repl. What about to include `vim-mode`/`vim-mode-plus` class attribute to selectors linked with __atom-text-editor__?

**Comment by geksilla** [comment]
:disappointed: not working(

**Comment by spencerlyon2** [comment]
Hmm... Not sure what the right thing to do here is. It would be super hacky to add vim mode class attributes to the `.ink.console`. 

I don't have other ideas right now, but will post here if I get one

**Comment by dvcrn** [comment]
How about a rule like `input:not([type="text"])`. We catch everything except textbox inputs

**Comment by geksilla** [comment]
@dvcrn agree, we have to avoid capturing of `textarea` and `input` when `vim-mode` or `vim-mode-plus` activated. I will try to fix this today.

**Comment by geksilla** [comment]
Should be ok now. Ignore tags `input` and `textarea`. When target is `atom-text-editor` check for classes `vim-mode` or `vim-mode-plus`, ignore attributes `mini`, ignore classes `insert-mode` and `mini`.

**Comment by dvcrn** [comment]
@spencerlyon2 can you test this again with the Julia repl?

**Comment by spencerlyon2** [comment]
Triggers which key in the tree view, but not the REPL -- perfect!

**Comment by dvcrn** [comment]
screen shot 2016-01-07 at 10 29 52 am

whoa it even works in settings! :D amazing job!

**Comment by spencerlyon2** [comment]
Nice! let's merge!

**Comment by dvcrn** [comment]
After codereview :smile: Will do that later

**Comment by dvcrn** [comment]
@geksilla I noticed that we no longer remove the `.vim-mode` or `.vim-mode-plus` classes. The reason why I removed that is to block all related vim keybindings from triggering. 

I noticed that `space g` for example is waiting for the atom timeout before it can resolve to the git menu

**Comment by geksilla** [comment]
@dvcrn, I see will send another PR with removing class name.

**Pull request merged**
