### PR TITLE
feat(core): Added which-key delay option.

### PR DESCRIPTION
**Pull request by geksilla**
Added option `proton.core.whichKeyDelay` to core layer.
ping @spencerlyon2  to check this out.

### CODE REVIEW

**Comment by spencerlyon2** [comment]
@geksilla thanks for working on this! 

I have a couple of comments:

- It would be great if the window dim didn't happen until which-key is displayed for the first time.
- Right now the delay is applied to every page of which-key. What I had in mind was a delay for having it show up the first time, but then have all updates after that be immediate. For example, if I'm doing `SPC f s`, nothing visual happens when I press `SPC` until after the delay. Assuming I waited long enough for which -key to pop up, when I hit `f` it immediately brings me into the file page rather than after the delay

**Comment by geksilla** [comment]
> It would be great if the window dim didn't happen until which-key is displayed for the first time.

:+1: 

> Right now the delay is applied to every page of which-key. What I had in mind was a delay for having it show up the first time, but then have all updates after that be immediate. For example, if I'm doing SPC f s, nothing visual happens when I press SPC until after the delay. Assuming I waited long enough for which -key to pop up, when I hit f it immediately brings me into the file page rather than after the delay

I think that delay per each key press feels more natural. Really like it from spacemacs experience. What about to add __boolean__ option like `proton.core.whichKeyDelayOnInit` to enable described behavior?

**Comment by spencerlyon2** [comment]
Hmm, good catch. For some reason I thought the delay was only on the initial key press. 

I'd be happy to follow space macs here, but having an option like you described would be even better!

**Comment by geksilla** [comment]
Ok, I will update this PR soon.

**Comment by geksilla** [comment]
@spencerlyon2 you can check new option `proton.core.whichKeyDelayOnInit` and there is no dim until which-key become visible.

**Comment by spencerlyon2** [comment]
Looking good!

One more comment : I believe that when we reach the end of a chain where which-key has been displayed (i.e. after `SPC f s`) there is a delay to having which key disappear. It would be great if the panel was removed immediately when a chain terminates.

**Comment by geksilla** [comment]
I think this delay caused by executed command. In your case `SPC f s` calls file save and there is an issue regarding micro hangs on file saving. I didn't change code for which-key hiding and from the code we deactivate proton, hide which-key panel and after that executing command.

**Comment by spencerlyon2** [comment]
Yep, this seems good to me!

My nit-picking is officially over. Thanks again for implementing.

**Comment by geksilla** [comment]
Thanks for comments!

**Comment by geksilla** [comment]
Added option to disable which-key modal.

**Comment by dvcrn** [comment]
@geksilla is this ready for merge?

**Comment by geksilla** [comment]
@dvcrn, yes, should works as well

**Pull request merged**
