### PR TITLE
Window shortcuts

### PR DESCRIPTION
**Pull request by jessejanderson**
Adds the following shortcuts:

`SPC w -` split pane down
`SPC w /` split pane right
`SPC w H` move pane left
`SPC w J` move pane down
`SPC w K` move pane up
`SPC w L` move pane right

Adds the package `move-panes`

### CODE REVIEW

**Comment by dvcrn** [comment]
Can you rebase this please?

**Comment by jessejanderson** [comment]
Coo - had some git issues but all should be well now.

**Comment by robbyoconnor** [comment]
I want this

**Comment by jessejanderson** [comment]
Added:

`SPC H` move pane left
`SPC J` move pane down
`SPC K` move pane up
`SPC L` move pane right

**Comment by dvcrn** [comment]
could you please rebase and try to re-compile this? I had some problems testing this

**Comment by jessejanderson** [comment]
Yah, away from computer - will take a look later.

**Comment by jessejanderson** [comment]
I may have bitten off more than I can chew if this still isn't working for you. Let me know if this compiles for you.

**Comment by geksilla** [comment]
`move-panes` works with `vim-mode` as well.  But with `vim-mode-plus` throws error. Let me file an issue for `vim-mode-plus`.

**Comment by geksilla** [comment]
Issue was fixed in `vim-mode-plus`! Tested with latest version.
Thanks @t9md for quick response.
Before testing be sure that 0.21.0 `vim-mode-plus` version installed.
:+1:

**Comment by geksilla** [comment]
@jessejanderson can you please rebase this one. I'm ok with changes provided with this PR + one more thing, please use `:slash` keyword instead of `:/`. Thanks.

**Pull request merged**
