### PR TITLE
feat(spotify): add spotify layer

### PR DESCRIPTION
**Pull request by jmartin84**
A new layer is added to the fun section that wraps the spotify-remote package

https://github.com/theHazzard/spotify-remote

### CODE REVIEW

**Comment by jmartin84** [comment]
This is currently untested. I was unclear from the readme on how to test the layer, but if someone could give me some direction there I will gladly do some testing

**Comment by dvcrn** [comment]
Cool! :) Thanks for the contribution!

For testing, delete your apm version of proton mode and compile it locally. There's a guide section in the README here - https://github.com/dvcrn/proton/blob/master/README.md#requirements. After compiling (with `lein run -m build/dev` for example) and linking, restart atom and it should load your local version of proton-mode. 

For feedback, I think we could leave out the `:m` and just put it under `a s` for spotify. If we get more music apps in the future we could always relocate it

**Comment by jmartin84** [comment]
no problem, I only put in the m layer to mirror the spacemacs spotify layer anyway.

**Comment by dvcrn** [comment]
Hey @jmartin84, were you able to test this PR on your machine? 
I don't use spotify myself which makes this a bit difficult for me to evaluate

**Comment by jmartin84** [comment]
@dvcrn I haven't been able to get back to it yet - I should have some time this weekend and will post and update soon. Thanks!

**Comment by dvcrn** [comment]
I'm closing this for now. If someone with a Spotify account wants to pick this up, please go for it!

**Pull request closed without merging**
